controllers/PersonalController.php
<?php

namespace app\controllers;

use yii;
use app\models\Personal;
use app\models\Pegawai;
use app\models\PersonalSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PersonalController implements the CRUD actions for Personal model.
 */
class PersonalController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Personal models.
     *
     * @return string
     */
    public function actionIndex()
    {   
        
        $searchModel = new PersonalSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        // $dataProvider->query->where(['jenis_kelamin'=>'laki-laki']);//selec where jenis_kelamin = 'laki-laki'
   
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Personal model.
     * @param int $id_personal Id Personal
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id_personal)
    {
        return $this->render('view', [
            'model' => $this->findModel($id_personal),
        ]);
    }

    /**
     * Creates a new Personal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Personal();
        $modelPegawai = new Pegawai();
        $statusPerkawinan = Personal::STATUS_PERKAWINAN;
        $agama = Personal::AGAMA;
        $pendidikan = Personal::PENDIDIKAN;

        $jenis_pegawai = Pegawai::JENIS_PEGAWAI;
        $status_pegawai = Pegawai::STATUS_PEGAWAI;
        $nama_personal = Personal::getAllPersonal();
        
        // echo "<pre>";
        // print_r($_POST);die();
        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $modelPegawai->load($this->request->post())){
              
              $transaction = Yii::$app->db->beginTransaction();
                try {
                    $model->tgl_lahir = \Yii::$app->formatter->asDate($model->tgl_lahir,'yyyy-MM-dd'); 
                    if (!$model->save()) {
                        throw new \Exception('Gagal menyimpan Personal : ' .json_encode($model->getErrors()));
                        
                    }


                    $modelPegawai->id_personal = Yii::$app->db->getLastInsertID();
                    $modelPegawai->tgl_bergabung = \Yii::$app->formatter->asDate($modelPegawai->tgl_bergabung,'yyyy-MM-dd');
                    
                    if (!$modelPegawai->save()) {
                       throw new \Exception('Gagal menyimpan Pegawai :' .json_encode($modelPegawai->getErrors()));
                    }

                    Yii::$app->getSession()->setFlash('success', [
                        'text' => 'Sukses !',
                        'title' => 'Data Berhasil Disimpan',
                        'type' => 'success',
                        'timer' => 5000,
                        'showConfirmButton' => false
                    ]);
                    $transaction->commit();
                    return $this->redirect(['view', 'id_personal' => $model->id_personal]);
                } catch (\Exception $e) {
                    $transaction->rollBack();
                   
                     Yii::$app->getSession()->setFlash('error', [
                        'text' =>  $e->getMessage(),
                        'title' => 'Data Gagal Disimpan',
                        'type' => 'error',
                        'timer' => 10000,
                        'showConfirmButton' => false
                    ]);
                     return $this->redirect(Yii::$app->request->referrer);
                    // throw $e;
                }
               
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            'modelPegawai'=>$modelPegawai,
            'statusPerkawinan'=>$statusPerkawinan,
            'agama'=>$agama,
            'pendidikan'=>$pendidikan,
            'nama_personal'=>$nama_personal,
            'jenis_pegawai'=>$jenis_pegawai,
            'status_pegawai'=>$status_pegawai,
        ]);
    }

    /**
     * Updates an existing Personal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id_personal Id Personal
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id_personal)
    {
        $statusPerkawinan = Personal::STATUS_PERKAWINAN;
        $agama = Personal::AGAMA;
        $pendidikan = Personal::PENDIDIKAN;
        $model = $this->findModel($id_personal);
        $modelPegawai = new Pegawai();
        $jenis_pegawai = Pegawai::JENIS_PEGAWAI;
        $status_pegawai = Pegawai::STATUS_PEGAWAI;
        $model->tgl_lahir = date('d-M-Y',strtotime($model->tgl_lahir));
        // var_dump($model->tgl_lahir); die();
        
            if ($model->load($this->request->post())){
                $model->tgl_lahir = \Yii::$app->formatter->asDate($model->tgl_lahir,'yyyy-MM-dd');
             
                $model->save();
                return $this->redirect(['view', 'id_personal' => $model->id_personal]);
            }
        

        return $this->render('update', [
            'model' => $model,
            'modelPegawai' => $modelPegawai,
            'jenis_pegawai' => $jenis_pegawai,
            'status_pegawai' => $status_pegawai,
            'statusPerkawinan'=>$statusPerkawinan,
            'agama'=>$agama,
            'pendidikan'=>$pendidikan,
        ]);
    }

    /**
     * Deletes an existing Personal model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id_personal Id Personal
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id_personal)
    {
        $this->findModel($id_personal)->delete();
        Yii::$app->getSession()->setFlash('error', [
            'text' =>  'Deleted',
            'title' => 'Data Berhasil Dihapus',
            'type' => 'error',
            'timer' => 10000,
            'showConfirmButton' => false
        ]);                            
        return $this->redirect(['index']);
    }

    /**
     * Finds the Personal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id_personal Id Personal
     * @return Personal the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id_personal)
    {
        if (($model = Personal::findOne(['id_personal' => $id_personal])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/**
 * @var string $content
 * @var \yii\web\View $this
 */
use app\widgets\Alert;
use yii\widgets\Breadcrumbs;
use yii\helpers\Html;
use app\assets\AppAsset;
use aryelds\sweetalert\SweetAlert;
use yii\helpers\Url;

AppAsset::register($this);

?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="nav-<?= !empty($_COOKIE['menuIsCollapsed']) && $_COOKIE['menuIsCollapsed'] == 'true' ? 'sm' : 'md' ?>" >
<?php $this->beginBody(); ?>
<div class="container body">

    <div class="main_container">

        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">

                <div class="navbar nav_title" style="border: 0;">
                    <a href="/" class="site_title"><i class="fa fa-paw"></i> <span>CRUD YII2</span></a>
                </div>
                <div class="clearfix"></div>

                <!-- menu prile quick info -->
                <div class="profile">
                    <div class="profile_pic">
                        <img src="<?php echo Url::base(true)?>/images/img.jpg" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>Welcome,</span>
                        <h2>John Doe</h2>
                    </div>
                </div>
                <!-- /menu prile quick info -->

                <br />

                <!-- sidebar menu -->
               <?php 
                    $this->beginContent('@app/views/layouts/production/sidebar-menu.php');
                    $this->endContent();
                ?>
                <!-- /sidebar menu -->

                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                    <a data-toggle="tooltip" data-placement="top" title="Settings">
                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Lock">
                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Logout">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    </a>
                </div>
                <!-- /menu footer buttons -->
            </div>
        </div>

        <!-- top navigation -->
        <?php 
        $this->beginContent('@app/views/layouts/production/header.php');
        $this->endContent();
        ?>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
            <?php if (isset($this->params['h1'])): ?>
                <div class="page-title">
                    <div class="title_left">
                        <h1><?= $this->params['h1'] ?></h1>
                    </div>
                    <div class="title_right">
                        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="clearfix"></div>
                <div class="container">
                    <?= Breadcrumbs::widget([
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    ]) ?>
                    <?php 
                    foreach (Yii::$app->session->getAllFlashes() as $message) {
                       echo SweetAlert::widget([
                        'options' => [
                            'title' => (!empty($message['title'])) ? Html::encode($message['title']) : 'Title Not Set!',
                            'text' => (!empty($message['text'])) ? Html::encode($message['text']) : 'Text Not Set!',
                            'type' => (!empty($message['type'])) ? $message['type'] : SweetAlert::TYPE_INFO,
                            'timer' => (!empty($message['timer'])) ? $message['timer'] : 5000,
                            'showConfirmButton' =>  (!empty($message['showConfirmButton'])) ? $message['showConfirmButton'] : true
                        ]
                    ]);
                    }

                     ?>
                    <?= $content ?>
                </div>
        </div>
        <!-- /page content -->
        <!-- footer content -->
        <footer>
            <div class="pull-right">
                CRUD YII2 - Pintar Coding 
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>

</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
</div>
<!-- /footer content -->
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

views/layouts/main_login.php
<?php

/**
 * @var string $content
 * @var \yii\web\View $this
 */
use app\widgets\Alert;
use yii\widgets\Breadcrumbs;
use yii\helpers\Html;
use app\assets\AppAsset;
use aryelds\sweetalert\SweetAlert;
use yii\helpers\Url;

AppAsset::register($this);

?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login" >
<?php $this->beginBody(); ?>
<div class="container body">
        <div class="container">
            <?php 
            foreach (Yii::$app->session->getAllFlashes() as $message) {
               echo SweetAlert::widget([
                'options' => [
                    'title' => (!empty($message['title'])) ? Html::encode($message['title']) : 'Title Not Set!',
                    'text' => (!empty($message['text'])) ? Html::encode($message['text']) : 'Text Not Set!',
                    'type' => (!empty($message['type'])) ? $message['type'] : SweetAlert::TYPE_INFO,
                    'timer' => (!empty($message['timer'])) ? $message['timer'] : 5000,
                    'showConfirmButton' =>  (!empty($message['showConfirmButton'])) ? $message['showConfirmButton'] : true
                ]
            ]);
           }?>
         <div class="col-md-4"></div>
         <div class="col-md-4"><?= $content ?></div>
     </div>
</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
</div>
<!-- /footer content -->
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

views/layouts/main_old.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            ['label' => 'Personal', 'url' => ['/personal/index']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">&copy; My Company <?= date('Y') ?></p>
        <p class="float-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>